# Generated by Django 5.2 on 2025-04-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsslider',
            name='cms_css',
            field=models.CharField(default='_', max_length=200, null=True, verbose_name='CSS класс'),
        ),
    ]
