# Generated by Django 5.2 on 2025-05-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_chat', models.CharField(max_length=200, verbose_name='чат айди')),
                ('tg_message', models.TextField(verbose_name='Текст')),
                ('tg_token', models.CharField(max_length=50, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
