# Generated by Django 5.2 on 2025-04-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now=True)),
                ('order_name', models.CharField(max_length=50)),
                ('order_phonenumber', models.CharField(max_length=50)),
            ],
        ),
    ]
